project:
  type: website

website:
  title: "Prepratory Labs"
  navbar:
    left:
      - href: slide_deck.qmd
        text: Slide Deck

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



