project:
  type: website

website:
  title: "Preparatory Labs"
  navbar: false 
  # navbar:
  #   left:
  #     - text: Slide Deck
  #       href: slide_deck.qmd
  #     - text: "Module 1"
  #       menu:
  #         - text: "Lecture Notes"
  #           href: M1/M1_resources.qmd
  #         - text: "Additional Resources"
  #           href: M1/M1_technicalhelp.qmd
  #         - text: "Test Yourself"
  #           href: M1/M1_testyourself.qmd
  #         - text: "Exercise"
  #           href: M1/M1_exercise.qmd
  #     - text: "Module 2"
  #       menu:
  #         - text: "Lecture Notes"
  #           href: M2/M2_resources.qmd
  #         - text: "Additional Resources"
  #           href: M2/M2_technicalhelp.qmd
  #         - text: "Test Yourself"
  #           href: M2/M2_testyourself.qmd
  #         - text: "Exercise"
  #           href: M2/M2_exercise.qmd
  #     - text: "Module 3"
  #       menu:
  #         - text: "Lecture Notes"
  #           href: M3/M3_resources.qmd
  #         - text: "Additional Resources"
  #           href: M3/M3_technicalhelp.qmd
  #         - text: "Test Yourself"
  #           href: M3/M3_testyourself.qmd
  #         - text: "Exercise"
  #           href: M3/M3_exercise.qmd
      # - text: "Module 4"
      #   menu:
      #     - text: "Lecture Notes"
      #       href: M2/M2_resources.qmd
      #     - text: "Additional Resources"
      #       href: M2/M2_technicalhelp.qmd
      #     - text: "Test Yourself"
      #       href: M2/M2_testyourself.qmd
      #     - text: "Exercise"
      #       href: M2/M2_exercise.qmd
      # - text: "Module 5"
      #   menu:
      #     - text: "Lecture Notes"
      #       href: M4/M4_resources.qmd
      #     - text: "Additional Resources"
      #       href: M4/M4_technicalhelp.qmd
      #     - text: "Test Yourself"
      #       href: M4/M4_testyourself.qmd
      #     - text: "Exercise"
      #       href: M4/M4_exercise.qmd
      # - text: "Module 6"
      #   menu:
      #     - text: "Lecture Notes"
      #       href: M2/M2_resources.qmd
      #     - text: "Additional Resources"
      #       href: M2/M2_technicalhelp.qmd
      #     - text: "Test Yourself"
      #       href: M2/M2_testyourself.qmd
      #     - text: "Exercise"
      #       href: M2/M2_exercise.qmd
      # - text: "Module 7"
      #   menu:
      #     - text: "Lecture Notes"
      #       href: M7/M7_resources.qmd
      #     - text: "Additional Resources"
      #       href: M7/M7_technicalhelp.qmd
      #     - text: "Test Yourself"
      #       href: M7/M7_testyourself.qmd
      #     - text: "Exercise"
      #       href: M7/M7_exercise.qmd
format:
  html:
    theme: [cosmo, ./scss/theme.scss]
    css: [./css/styles.css]
    toc: true
    grid:
      sidebar-width: 100px
      body-width: 1000px
      margin-width: 400px
      gutter-width: 1.5rem

# Set default options for every webpage that may or may not include webR.
webr: 
  show-startup-message: false    # Display status of webR initialization
  show-header-message: false     # Check to see if COOP&COEP headers are set for speed.
#  packages: ['ggplot2', 'dplyr'] # Pre-install dependencies
#  base-url: ''                   # Base URL used for specifying where R WebAssembly binaries should be located
#  home-dir: '/home/rstudio'      # Customize where the working directory is
#  channel-type: 'post-message'   # Specify communication channel
#  service-worker-url: ''         # URL from where to load JavaScript worker scripts when loading webR with the ServiceWorker communication channel.

# Attach webR to every page
filters:
  - webr

